#!/bin/bash

declare RED="\e[31m"
declare GREEN="\e[32m"
declare CYAN="\e[36m"
declare DEFAULT="\e[39m"

function compare() {
    declare title="$1"
    declare actual="$2"
    declare root=2.25.
    declare expected="${root}$3"
    echo -e "${CYAN}${title}${DEFAULT}"
    if [[ $actual = $expected ]]; then
        echo -e "${GREEN}PASSED${DEFAULT}"
        passed=$((passed+1))
        return 0
    else
        echo "actual: ${actual}"
        echo "expect: ${expected}"
        echo -e "${RED}FAILED${DEFAULT}"
        failed=$((failed+1))
        return 1
    fi
}

function get_tag() {
    ./get-tag "${out}" "$1"
}

function verify_media_storage_sop_instance_uid() {
    declare expected="$1"
    declare actual=$(get_tag 0002,0003)
    compare "Media Storage SOP Instance UID" "${actual}" "${expected}"
}

function verify_sop_instance_uid() {
    declare expected="$1"
    declare actual=$(get_tag 0008,0018)
    compare "SOP Instance UID" "${actual}" "${expected}"
}

function verify_study_instance_uid() {
    declare expected="$1"
    declare actual=$(get_tag 0020,000d)
    compare "Study Instance UID" "${actual}" "${expected}"
}

function verify_series_instance_uid() {
    declare expected="$1"
    declare actual=$(get_tag 0020,000e)
    compare "Series Instance UID" "${actual}" "${expected}"
}

function verify_frame_of_reference_uid() {
    declare expected="$1"
    declare actual=$(get_tag 0020,0052)
    compare "Frame of Reference UID" "${actual}" "${expected}"
}

declare file="${1:-single-dicom.dcm}"
declare passed=0
declare failed=0
declare out=out.dcm

gdcmanon -i ${file} -o ${out} -c dummy-cert.cer
verify_media_storage_sop_instance_uid 67853465656486509836044414130127674991
verify_sop_instance_uid 67853465656486509836044414130127674991
verify_study_instance_uid 332727874506492441949635753637643565296
verify_series_instance_uid 227474913195701685931351941259382086518
verify_frame_of_reference_uid 42081261005830073329032663122232811329

rm ${out}
declare result="TOTAL PASSED: ${passed} FAILED: ${failed}"
if [[ ${failed} -gt 0 ]]; then
    echo -e "${RED}${result}${DEFAULT}"
else
    echo -e "${GREEN}${result}${DEFAULT}"
fi
exit ${failed}
